# Generated by Django 4.2.2 on 2023-06-10 07:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('result', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.test')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_text', models.TextField(max_length=400)),
                ('option_a', models.TextField(max_length=200)),
                ('option_b', models.TextField(max_length=200)),
                ('option_c', models.TextField(max_length=200)),
                ('option_d', models.TextField(max_length=200)),
                ('correct_answer', models.CharField(max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.test')),
            ],
        ),
    ]
