# Generated by Django 4.2.2 on 2023-06-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_test_form_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_form',
            name='answers',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
